### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by mat007** [simonferquel/simcim#1]
Hi @simonferquel, how are you? 😁 

Would it be possible to have a license for this library?

Thanks!

**Comment by simonferquel** [comment]
Sure ! :D
If you make a PR with an Apache license file, I'll be glad to merge it !

**Comment by simonferquel** [comment]
How things are going at Docker By the way ?

**Comment by mat007** [comment]
There you go: #2 😁 

> How things are going at Docker By the way ?

Good, same old same old!
Also summer holidays are looming 😄
